# Copyright (c) 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

include config.mk
VALID_TOOLCHAINS := newlib glibc pnacl

#
# We use the chrome.experimental.identity API, which requires the
# --enable-experimental-expension-apis flag.
#
CHROME_ARGS += --enable-experimental-extension-apis

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/../../..)
include $(NACL_SDK_ROOT)/tools/common.mk

TARGET = hnef
LIBS = nacl_io ppapi pthread

CFLAGS = -Wall
DIR_SRCLANG=	srclang
DIR_RULES=	rules

FILE_LANG=	$(DIR_SRC)/lang.c
DIR_SRC=	src
DIRS_SRC=	$(shell find $(DIR_SRC) -type d)
SOURCES=		$(foreach SDIR, $(DIRS_SRC), $(wildcard $(SDIR)/*.c))
INC=		$(foreach SDIR, $(DIRS_SRC), $(wildcard $(SDIR)/*.h))
INC_DIRS=	$(patsubst %, -I%, $(DIRS_SRC))
#SOURCES = drive.cc

$(FILE_LANG):
	cp -v $(DIR_SRCLANG)/lang_$(LANGUAGE).c $(FILE_LANG)

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(MACROS) $(CFLAGS) $(INC_DIRS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
